name: tour_de_france
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_dotenv: ^5.2.1
  flutter_launcher_icons: ^0.14.3
  flutter_markdown: ^0.7.7
  flutter_native_splash: ^2.4.5
  fpdart: ^1.1.1
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  hydrated_bloc: ^10.0.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  supabase_flutter: ^2.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/images/
    - assets/gif/
    - README.md
